#!/usr/bin/env bash 
 # Installs Nginx with the following configurations: 
 #+    Listens on port 80. 
 #+    Returns a page containing "Hello World!" when queried 
 #++    at the root with a curl GET request. 
  
 sudo apt-get update 
 sudo apt-get install -y nginx 
   
 sudo chown -R ubuntu /var/www/html 
 sudo chmod -R 755 /var/www/html/index.nginx-debian.html
 
 echo "Hello World!" > /var/www/html/index.nginx-debian.html

 cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
  
 sudo service nginx restart
